### ISSUE TITLE
grpc-web, XhrClientConnection sets certain headers twice

### ISSUE THREAD

**Issue by yiransheng** [grpc/grpc-dart#381] opened 2020-11-03 14:21 UTC
XhrClientConnection's implementation may set these http headers twice:

* Content-Type
* X-User-Agent
* X-Grpc-Web

This is problematic, for instance, when running flutter web (in browser platform). I believe it is expected for grpc-web to have this header:

```
X-Grpc-Web: 1
```
However, if this is set twice via underlying XHttpRequest api (calling `request.setRequestHeader('X-Grpc-Web', '1');`  twice) would produce the following instead (in latest Chrome browser):

```
X-Grpc-Web: 1, 1
```
...thus breaking the protocol.

<master>

## Repro steps

1. Initialize `GrpcWebClientChannel` client
2. Make any grpc-web api calls, leave CallOptions.metadata's `Content-Type` empty

Expected result: grpc-web requests successful

Actual result: indeterminate errors, usually timeout (in my case the api call was interpreted as a native grpc call by envoy proxy)

## Details

The offending code:

1. https://github.com/grpc/grpc-dart/blob/cb1c0ea8b3339e3497ca5d9abbbc8387dc085938/lib/src/client/transport/xhr_transport.dart#L188

When content type metadata from CallOptions is null, `XhrClientConnection` will fill in some defaults.

2. sometime later:
https://github.com/grpc/grpc-dart/blob/cb1c0ea8b3339e3497ca5d9abbbc8387dc085938/lib/src/client/transport/xhr_transport.dart#L169

It copies metadata into http request headers.

3. however, immediately after:
https://github.com/grpc/grpc-dart/blob/cb1c0ea8b3339e3497ca5d9abbbc8387dc085938/lib/src/client/transport/xhr_transport.dart#L174

The same header is set again, introducing the erroneous header values described above.

Equivalent compiled javaScript code:
```javascript
function setHeadersTwice() {
  const xhr = new XMLHttpRequest();
  xhr.open('POST', 'https://example.com');
  xhr.setRequestHeader('X-Grpc-Web', '1');
  xhr.setRequestHeader('X-Grpc-Web', '1');
  xhr.send();
}
```
Reference form MDN:

> Each time you call setRequestHeader() after the first time you call it, the specified text is appended to the end of the existing header's content.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader

**Comment by mraleph** [comment] 2020-11-05 19:21
Duplicate of #380

**Comment by mraleph** [comment] 2020-11-05 19:22
Thanks for the report. 

We are going to revert offending change and publish a fixed version of the package, but most likely this is not going to happen earlier than next week.

**Closed by mraleph** 2020-11-05 19:21 UTC
