### ISSUE TITLE
The system can't find the specified file

### ISSUE THREAD

**Issue by gfh21cn** [grpc/grpc-dart#74] opened 2018-03-25 14:15 UTC
Operation based on document hints
I'm using windows10, to prompt errors when using the protoc tool to generate dart files

step 1:
pub global activate protoc_plugin

step 2: add to PATH :
![image](https://user-images.githubusercontent.com/18669068/37875992-3a64f62c-3079-11e8-94b1-93b6048876ec.png)

error info:
![image](https://user-images.githubusercontent.com/18669068/37875980-148189d4-3079-11e8-806c-fe40136e94df.png)

error message (translate):  The system can't find the specified file

**Comment by nevi-me** [comment] 2018-03-26 14:47
Hi @gfh21cn, this is a duplicate of #71

**Comment by mit-mit** [comment] 2018-07-04 06:32
assigning to self to see if we can update the docs for this

**Comment by nevi-me** [comment] 2018-07-04 06:40
@mit-mit it might be a broader protoc issue on Windows, because even with JS and Python, I have to specify full path. Haven't tried on Linux though.

**Comment by mit-mit** [comment] 2018-07-04 06:43
cc @LisaFC, have you encountered this issue before?

**Comment by nevi-me** [comment] 2018-07-04 10:36
@LisaFC @mit-mit I'll try reproduce it this evening UTC, otherwise I'll retract my statement. Then it might be a case of documenting the behaviour on the dart-protoc-plugin README.

**Comment by denniskaselow** [comment] 2018-08-24 07:13
On a hunch I renamed `protoc-gen-dart.bat` to `protoc-gen-dart.exe` et voila, protoc tries to run it, which obviously fails.

So the reason it does not work is, because protoc is looking for a `protoc-gen-dart.exe` but the file is actually `protoc-gen-dart.bat`.

**Comment by sigurdm** [comment] 2018-08-24 10:46
I guess we either need to construct a bin/protoc-gen-dart.exe that does what the bat file does or convince protoc to search for bat files as well as exe files. Not sure what is easier.

**Comment by denniskaselow** [comment] 2018-08-25 07:39
I think it would be easier to also search for `.bat` files in `protoc`.

This is the code that searches for the exe: https://github.com/protocolbuffers/protobuf/blob/d9ccd0c0e6bbda9bf4476088eeb46b02d7dcd327/src/google/protobuf/compiler/subprocess.cc#L133

And from the docs of [CreateProcessA](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa) (`lpApplicationName` being the first and `lpCommandLine` being the second parameter):

> To run a batch file, you must start the command interpreter; set lpApplicationName to cmd.exe and set lpCommandLine to the following arguments: /c plus the name of the batch file.

So an additional `if` in the `else` block should do the trick.

**Comment by mit-mit** [comment] 2018-08-27 14:56
cc @jayantkolhe, any tips for who to discuss with if protoc could also support `.bat` (see details in https://github.com/grpc/grpc-dart/issues/74#issuecomment-415949609) on Windows?

**Comment by jtattermusch** [comment] 2018-08-28 09:56
@mit-mit  you can open a feature request in https://github.com/protocolbuffers/protobuf and describe why it's needed there.

**Comment by mit-mit** [comment] 2018-11-06 22:53
Closing, this was resolved in https://github.com/protocolbuffers/protobuf/issues/5084

**Closed by mit-mit** 2018-11-06 22:53 UTC
Labels: documentation
