### ISSUE TITLE
Please revert https://github.com/grpc/grpc-dart/pull/287 to fix server streaming for web.

### ISSUE THREAD

**Issue by gustav3d** [grpc/grpc-dart#345] opened 2020-09-06 19:33 UTC
Hello,

Regarding the broken server streaming for web.

The (old) workaround to stay on commit 39c7511 does not work anymore with flutter dev or master (android is broken(but thats not the point)).
Can the problematic commit (https://github.com/grpc/grpc-dart/pull/287) be reverted please ?. 

best regards
  Gustav

**Comment by mraleph** [comment] 2020-09-17 08:19
Duplicate of #306

**Comment by mraleph** [comment] 2020-09-17 08:19
We are going to revert.

**Closed by mraleph** 2020-09-17 08:19 UTC
Labels: type-bug
