### ISSUE TITLE
Server crash with several streams aborted

### ISSUE THREAD

**Issue by a14n** [grpc/grpc-dart#213] opened 2019-07-02 12:37 UTC
Quite similar to #147 but it happens when several streams was in progress on the same channel.

Tested on master branch (9d2a469)

## Repro steps

```yaml
# pubspec.yaml
name: issue_xxx
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  grpc:
    path: ../../
  protobuf: ^0.10.1
  stack_trace: any
  args: ^1.5.1
dev_dependencies:
  test: ^1.3.0
```

```proto
// sample.proto
syntax = "proto3";
package bug;
message Empty {}
message Hello {
    string hello = 1;
}
service BugService {
    rpc infiniteStream (Empty) returns (stream Hello) {}
}
```

```dart
// bin/server.dart
import 'dart:async';
import 'package:grpc/grpc.dart' as grpc;
import 'package:issue_xxx/src/generated/sample.pb.dart';
import 'package:issue_xxx/src/generated/sample.pbgrpc.dart';

class BugService extends BugServiceBase {
  final infiniteStreamController = StreamController<Hello>.broadcast();
  int count = 0;

  BugService() {
    Timer.periodic(Duration(seconds: 1), (_) {
      count++;
      infiniteStreamController.add(Hello()..hello = 'Hello $count');
    });
  }

  @override
  Stream<Hello> infiniteStream(grpc.ServiceCall call, Empty request) async* {
    try {
      yield* infiniteStreamController.stream;
    } finally {
      print('finished');
    }
  }
}

main(List<String> args) async {
  // Run the gRPC server.
  final server = new grpc.Server([new BugService()]);
  await server.serve(port: 8080);
  print('Server listening on port ${server.port}...');
}
```

```dart
// bin/client.dart
import 'dart:async';

import 'package:grpc/grpc.dart';
import 'package:issue_xxx/src/generated/sample.pb.dart';
import 'package:issue_xxx/src/generated/sample.pbgrpc.dart';

main(List<String> args) async {
  final channel = ClientChannel(
    'localhost',
    port: 8080,
    options: const ChannelOptions(
      credentials: const ChannelCredentials.insecure(),
    ),
  );
  final client = BugServiceClient(channel);

  // listen 2 streams to trigger the crash (only one subscription doesn't lead to crash)
  client.infiniteStream(Empty()).listen(print);
  client.infiniteStream(Empty()).listen(print);

  // exit program
  Future.delayed(Duration(seconds: 3), () => throw 'Boom');
}
```

* Start `bin/server.dart`
* Start `bin/client.dart`
* After 3s the server crash.

Expected result: The server doesn't crash
Actual result: The server does crash

## Details

Instead of having 2 _finished_ line in logs, only one is displayed and an unhandled error occurs.

```
Server listening on port 8080...
finished
Unhandled exception:
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:585:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#2      TransportStream.sendHeaders (package:http2/transport.dart:145:10)
#3      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:298:13)
#4      ServerHandler_._sendError (package:grpc/src/server/handler.dart:347:5)
#5      ServerHandler_._onResponse (package:grpc/src/server/handler.dart:236:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by sigurdm** [comment] 2019-07-19 13:34
Try this branch:
https://github.com/sigurdm/grpc-dart/tree/cancel_on_outgoing_done

I still think some things could be simplified. But I believe it will at least work.

**Comment by a14n** [comment] 2019-07-19 13:51
Awesome! The server don't crash anymore.

I will use this branch until it is merged :)

Thanks a lot!

**Comment by u007** [comment] 2020-05-20 15:32
is this grpc dead?

**Comment by mraleph** [comment] 2020-09-28 13:15
Duplicate of #67

**Closed by mraleph** 2020-09-28 13:15 UTC
Labels: type-bug
