### ISSUE TITLE
client intercept for adding metadata

### ISSUE THREAD

**Issue by girirajthara** [grpc/grpc-dart#348] opened 2020-09-14 10:52 UTC
Need of client intercept for adding metadata to a request

grpc:2.2.0

**Comment by mit-mit** [comment] 2020-09-17 11:06
@girirajthara are you looking for something similar to https://godoc.org/google.golang.org/grpc#UnaryClientInterceptor & https://godoc.org/google.golang.org/grpc#StreamClientInterceptor ?

**Comment by girirajthara** [comment] 2020-09-17 17:28
Yes I want to use it for adding auth id token to every rpc call, by using client interceptor.

**Comment by wayne-li2** [comment] 2020-09-22 01:40
Looks like #338 is in-review and should address this case :)

**Comment by mraleph** [comment] 2020-09-25 14:25
Duplicate of #121

**Closed by mraleph** 2020-09-25 14:25 UTC
Labels: type-enhancement

**Comment by zbigniew-mandziejewicz-3r** [comment] 2020-10-06 11:14
@girirajthara You can use `MetadataProvider`, it is specified in `CallOptions` that you can pass to `Client`.

**Comment by yingshaoxo** [comment] 2022-03-16 09:42
Can any one tell me how exactly I can use intercept with this package?

I simply want to interact with a rust grpc service, it has the interceptor in it.

https://github.com/hyperium/tonic/blob/master/examples/src/interceptor/server.rs
