### ISSUE TITLE
Clients that fail to close connections can crash servers

### ISSUE THREAD

**Issue by timburks** [grpc/grpc-dart#147] opened 2018-12-28 22:56 UTC
Following https://github.com/grpc/grpc-dart/issues/111, I find that a streaming client that fails to close a connection when it is killed can cause a Dart grpc server to crash. 

It appears that #111 was closed because well-written clients can now be closed safely, but when I tested with a client that did not call `channel.terminate();` on exit, I got the same crash and stack trace as reported in #111. This occurred with both the released (1.0.0) grpc library and on today's `master`.

## Steps to reproduce

pubspec.yaml:
```
name: sample

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  grpc: ^1.0.0
  protobuf: ^0.10.1
  args: ^1.5.1

dev_dependencies:
  test: ^1.3.0
```

protos/sample.proto:
```
syntax = "proto3";

package bug;

message Empty {}

message Hello {
    string hello = 1;
}

service BugService {
    rpc infiniteStream (Empty) returns (stream Hello) {}
}
```

bin/server.dart:
```
import 'dart:async';
import 'package:grpc/grpc.dart' as grpc;
import 'package:sample/src/generated/sample.pb.dart';
import 'package:sample/src/generated/sample.pbgrpc.dart';

class BugService extends BugServiceBase {
  final infiniteStreamController = StreamController<Hello>.broadcast();
  int count = 0;

  BugService() {
    Timer.periodic(Duration(seconds: 1), (_) {
      count++;
      infiniteStreamController.add(Hello()..hello = 'Hello $count');
    });
  }

  @override
  Stream<Hello> infiniteStream(grpc.ServiceCall call, Empty request) async* {
    await for (final hello in infiniteStreamController.stream) {
      yield hello;
    }
  }
}

main(List<String> args) async {
  // Run the gRPC server.
  final server = new grpc.Server([new BugService()]);
  await server.serve(port: 8080);
  print('Server listening on port ${server.port}...');
}
```

bin/client.dart:
```
import 'dart:async';
import 'dart:io';

import 'package:args/args.dart';
import 'package:grpc/grpc.dart';
import 'package:sample/src/generated/sample.pb.dart';
import 'package:sample/src/generated/sample.pbgrpc.dart';

main(List<String> args) async {
  var parser = new ArgParser();
  parser.addFlag('shutdown', defaultsTo: true);
  var results = parser.parse(args);
  var shutdown = results['shutdown'];

  final channel = ClientChannel(
    'localhost',
    port: 8080,
    options: const ChannelOptions(
      credentials: const ChannelCredentials.insecure(),
    ),
  );
  final client = BugServiceClient(channel);
  final completer = Completer<void>();
  final subscription = client.infiniteStream(Empty()).listen(print);
  if (shutdown) {
    ProcessSignal.sigint.watch().listen((_) async {
      await subscription.cancel();
      print('shutting down gracefully');
      await channel.terminate();
      completer.complete();
    });
  }
  await completer.future;
  exit(0);
}
```
Running the server with `dart bin/server.dart` and the client with `dart bin/client.dart`, killing the client with Control-C proceeds successfully because the client listens for SIGINT and closes the channel. But if the client is run with `dart bin/client.dart --no-shutdown` and then killed, the server crashes with the following trace:

```
Unhandled exception:
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:584:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#2      TransportStream.sendHeaders (package:http2/transport.dart:241:10)
#3      ServerHandler.sendTrailers (package:grpc/src/server/handler.dart:303:13)
#4      ServerHandler._sendError (package:grpc/src/server/handler.dart:352:5)
#5      ServerHandler._onResponse (package:grpc/src/server/handler.dart:241:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#14     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#15     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12
```

## Expected results

While it seems good to encourage clients to be well-behaved, I don't think we want a badly-written or malicious client to be able to crash a server by breaking a connection incorrectly.

(Is there something incorrect about the way the test server is written?)

**Comment by Kleak** [comment] 2019-01-22 13:36
Got the same error.
Also note that in a Flutter we can't get the event when an application is killed.
So we should absolutely not crash the server in that case.

**Comment by a14n** [comment] 2019-03-07 09:29
I face the same error. This is REALLY annoying.

Like #111 I suspect the issue is in the underlying http2 package.

@mkustermann, @sigurdm what do you think?

**Comment by aloisdeniel** [comment] 2019-03-27 09:48
Same error on my side, really dangerous for production environments. :/

**Comment by a14n** [comment] 2019-03-27 09:52
This issue sould be fixed with #156 . Meanwhile you can use the patch with:

```yaml
  grpc:
    git:
      url: https://github.com/a14n/grpc-dart.git
      ref: issue-147
```

(you can copy/fork my branch if you want to keep control on that)

**Comment by aloisdeniel** [comment] 2019-03-27 10:07
Thanks ! 👍

**Closed** 2019-04-03 12:57 UTC

**Comment by HyprUsr** [comment] 2025-12-16 22:45
Hey, is there any plan to fix this?

**Comment by mosuem** [comment] 2025-12-17 11:50
This should be fixed, this has been closed for 6 years now ;) If not, please open a new issue.
