### ISSUE TITLE
grpc 2.2.0 version critical issue with server streams

### ISSUE THREAD

**Issue by zs-dima** [grpc/grpc-dart#337] opened 2020-08-03 10:54 UTC
grpc 2.2.0 version do not works with server streams correctly
this version wait till server stream completed and then replay stream at once

older versions works well - they fire stream event as soon as it had been received.

grpc 2.2.0 - only this version have server streams issue

## Repro steps

1. Server side
await Task.Delay(TimeSpan.FromSeconds(10));
await responseStream.WriteAsync(new Msg(1));
await Task.Delay(TimeSpan.FromSeconds(10));
await responseStream.WriteAsync(new Msg(2));
. * . * . *

2. Client side - Actual result:
***************** 2020-08-03 13:43:26.685 Msg(1)
***************** 2020-08-03 13:43:26.686 Msg(2)

Expected result: 
***************** 2020-08-03 13:43:26.685 Msg(1)
***************** 2020-08-03 13:53:26.686 Msg(2)

Flutter version 
Reproduced on Beta version and Master 1.21.0-6.0.pre.142, guess all other versions behave the same

**Comment by mit-mit** [comment] 2020-09-17 11:11
cc @mraleph

**Comment by zs-dima** [comment] 2020-09-17 11:39
@mit-mit, @mraleph thanks a lot for looking into

**Comment by mraleph** [comment] 2020-09-21 07:16
Duplicate of #306

**Comment by mraleph** [comment] 2020-09-21 07:17
The problematic commit has been reverted. I am going to publish a new version today.

**Closed by mraleph** 2020-09-21 07:16 UTC
Labels: type-bug
