### ISSUE TITLE
grpc-web: Gracefully close a streaming connection

### ISSUE THREAD

**Issue by ligustah** [grpc/grpc-dart#206] opened 2019-06-26 19:08 UTC
Calling `cancel()` on the `ResponseStream` returned by a streaming RPC throws an exception.

version: 2.0.0+1

## Repro steps
Don't have separate code for this right now, but could prepare something if required.

1. Call a server-side streaming RPC
2. Receive messages
3. Call `cancel()` on the `ResponseStream`

Expected result: The connection is closed is closed and I can handle any possible exceptions.

Actual result: The code will throw two exceptions, only one of which I can catch.

## Details

I can see why adding an error to the stream when calling `cancel()` might be useful, but somewhere in the code it tries to add another error to one of the internal streams after that one was closed, which triggers the bad state exception seen below.

```
EXCEPTION: Bad state: Cannot add event after closing
STACKTRACE: 
dart:sdk_internal                                                                                addError
package:grpc/src/client/packages/grpc/src/client/call.dart 305:16                                [_onRequestError]
package:grpc/packages/grpc/src/client/transport/xhr_transport.dart 61:13                         <fn>

...

EXCEPTION: gRPC Error (1, Cancelled by client.)
STACKTRACE: 
package:grpc/src/client/packages/grpc/src/client/call.dart 324:18                                cancel
package:grpc/src/client/packages/grpc/src/client/common.dart 85:34                               cancel
```

Potentially related: #111

**Comment by softkot** [comment] 2020-09-23 13:57
I am confirming this annoying bug in 2.3.0

**Comment by mraleph** [comment] 2020-09-28 13:14
Duplicate of #67

**Comment by aragonet** [comment] 2020-12-15 09:52
The same is happening here on web with grpc version 2.8.0

**Closed** 2021-01-28 12:14 UTC
Labels: type-bug
