### ISSUE TITLE
gRPC Connection Error: Out Of Memory 

### ISSUE THREAD

**Issue by jyndrkhole** [grpc/grpc-dart#510] opened 2021-07-30 06:09 UTC
<short description>
When I connect to the local server at 127.0.0.1, I could connect to the server but when I try to connect with production-ready python server it throws an "Out Of Memory" error.
<version of the grpc-dart packages used; see your `pubspec.lock` file>
3.0.0

Expected result: Should connect to the remote server.

Actual result: It is throwing an error saying "Out Of Memory" every time I try connecting.

## Details

<img width="619" alt="Screenshot 2021-07-30 at 11 38 19 AM" src="https://user-images.githubusercontent.com/10459944/127608559-0b8e9959-3f27-496b-91a6-60e39642efbd.png">

**Comment by mraleph** [comment] 2021-08-09 10:26
Most likely duplicate of #458. Try to use the package version from master (e.g. by specifying `git` dependency on this repo) or check that your server is answering with valid gRPC protocol.

**Closed by mraleph** 2021-08-09 10:26 UTC
